project:
  type: website

website:
  title: "Mike Janssen, Ph.D."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:teaching
      - href: research.qmd
        text: Research
      - href: oer.qmd
        text: OER
      - about.qmd
      
  sidebar:
    - id: teaching
      title: "Teaching"
      background: light
      search: true
      collapse-level: 2
      style: "floating"      
      contents:        
        - teaching.qmd         
        - section: "Spring 2024"
          contents:
            - courses/emm/emm_s24.qmd
            - courses/nt/nt_s24.qmd
            - courses/ds/ds_s24.qmd
            - courses/ala/ala_s24.qmd 
        - section: "Fall 2023"
          contents:
            - courses/glm/glm_f23.qmd
            - courses/ra/ra_f23.qmd
            - courses/hom/hom_f23.qmd
        
      
      
format:
  html:
    theme:
        light: flatly
        dark: darkly
    css: styles.css
    toc: true


