---
title: "Research"
sidebar: false
---


My scholarly interests lie in three main areas: the intersections of commutative algebra, algebraic geometry, and graph theory; games on graphs; and scholarly teaching, including the use of mastery assessments and inquiry-based learning.


### Mathematics

My dissertation research was in the exploration of the so-called containment problem. In its most general form, one may ask, given a homogeneous ideal $I$, for which $m$ and $r$ is the symbolic power $I^{(m)}$ contained in the ordinary power $I^r$? In addition to exploring this question in my dissertation in the context of algebraic geometry, I explored a related question in the context of edge ideals $I(G)$. In that case, certain invariants of $I$ related to invariants of the underlying (simple) graph $G$.


### Scholarly teaching

I am also very interested in the use of research-based methods for teaching and assessment. As I describe [elsewhere](teaching), I am a proponent of active learning (thought of broadly) in all my courses, and I am also interested in the use of low-stakes, mastery-based assessments tied to clear standards for the purposes of encouraging mastery of fundamental skills and the development of a growth mindset in mathematics.



## Publications



* [Comparing Powers of Edge Ideals](https://doi.org/10.1142/S0219498819501846), _J. Alg. Appl._, Vol. 18, No. 10 (2019) (with T. Kamp and J. Vander Woude)
* [Mastery-based testing in undergraduate mathematics](https://doi.org/10.1080/10511970.2018.1488317), PRIMUS, Vol. 25, No. 5, 441-460 (2019). (with J.B. Collins, A. Harsy, J. Hart, K. Haymaker, A. Hoofnagle,  J. Stewart Kelly, A. Mohr, J. OShaughnessy)
* Start a Math Teacher Circle:  Connect K-12 Teachers with Engaging, Approachable, and Meaningful Mathematical  Problems, __The 21st Proceedings of the Association of Christians in the Mathematical Sciences__. (with T. Clark, A. Harsy, D. Klanderman, M. Maxwell, S. Robbert)
* [The Waldschmidt constant for squarefree monomial ideals](http://dx.doi.org/10.1007/s10801-016-0693-7), __J. Algbr Comb__, 2016,  (with C. Bocci,  S. Cooper, E. Guardo, B. Harbourne, U. Nagel, A. Seceleanu, A. Van Tuyl,  and T. Vu)
* [On the Fattening of Lines in $\mathbf{P}^3$](http://dx.doi.org/10.1016/j.jpaa.2014.05.033), Journal of Pure and Applied Algebra, 219(4):1055--1061, 2015, 
* [Containment problem for points on a reducible conic in $\mathbf{P}^2$](http://dx.doi.org/10.1016/j.jalgebra.2013.06.032), Journal of Algebra, 394(0):120--138, 2013, (with A. Denkert)

## Talks/Presentations

* _[On Symbolic Powers of Ideals](./talks/brianfest/Janssen-BrianFest.html)_, [Conference on Unexpected and Asymptotic Properties of Algebraic Varieties](https://math.unl.edu/brianfest2023), University of Nebraska-Lincoln, August 2023

* __A first experience in a flipped Calculus II course__, MAA Themed Contributed Paper Session on Flipped Classes: Implementation and Evaluation; Joint Mathematics Meetings; San Diego, CA, January 2018
*  __Cut Your Cake (And Eat It, Too!)__, MAA Themed Contributed Paper Session on ``My Favorite Math Circle Problem''; MathFest 2017; Chicago, IL, July 2017
* __An Overview of Specifications Grading__, 21st ACMS Biennial Conference; Charleston Southern University, Charleston, SC, May 2017
* __My Favorite Math Circle Problem: Cut Your Cake (And Eat It, Too!)__, 21st ACMS Biennial Conference; Charleston Southern University, Charleston, SC, May 2017
*  __Specifications Grading in a First Course in Abstract Algebra__,
         MAA Themed Contributed Paper Session on ``Teaching Abstract Algebra: Topics and Techniques''; Joint Mathematics Meetings 2017; Atlanta, GA, January 2017
*  __Improving proof-writing with reading guides__,
         MAA Themed Contributed Paper Session on Encouraging Early Career Teaching Innovation; MathFest 2016; Columbus, OH, August 2016
* __Implementing Specifications Grading in a Linear Algebra course__,
       	 MAA Session on Assessing Student Learning: Alternative Approaches; Joint Mathematics Meetings 2016; Seattle, WA, January 2016
* __The importance of $\alpha$__,
		MAA Invited Paper Session on Concrete Computations in Algebra and Algebraic Geometry; MathFest 2015; Washington, D.C., August 2015
* __Symbolic Powers of Ideals: Problems and Progress__ (15 minutes),
         20th ACMS Biennial Conference, Redeemer University College, Ancaster, Ontario, Canada, May 2015
* __Symbolic Powers of Ideals: Problems and Progress__ (50 minutes),
         Mathematics Seminar; University of South Dakota, March 2015
* __On the Fattening of Lines in $\mathbf{P}^3$__,
       	Oberwolfach Mini-Workshop 1508a,  Ideals of Linear Subspaces, Their Symbolic Powers and Waring Problems; Mathematisches Forschungsinstitut Oberwolfach; Oberwolfach, Germany, February 2015
* __On an Application of Bezout's Theorem__,
         Colloquium; Calvin College, February 2014
* __Ideals of almost collinear points in $\mathbb{P}^2$__,
         Special session on Interactions Between Algebraic Geometry and Commutative Algebra; Summer 2012 Meetings of the Canadian Mathematical Society; Regina, Saskatchewan, June 2012
* __Containment problem for ideals of points on a reducible conic__,
         Special session in Algebraic Geometry and Graded Commutative Algebra; Fall 2011 AMS Central sectional meeting; Lincoln, NE, October 2011
* __Results on the containment problem of ideals of fat points__,
         Algebraic Geometry Seminar; University of Nebraska-Lincoln, April 2010
* __What is Algebraic Geometry?__ (50 minutes),
         Geometry and Physics on Graphs REU; Canisius College; Buffalo, NY, July 2009
* __A Fifteen-Minute Survey of Nonunique Factorization__,
         IMMERSE at the University of Nebraska-Lincoln, July 2008